trigger:
- master

jobs:
- job: BuildLinuxWithSonarQube
  displayName: Build for Linux With SonarQube
  dependsOn: []
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    CC: gcc-7
    CXX: g++-7
  steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Peach'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-automake-linux-test'
      cliProjectName: 'geoffray-azure-automake-linux-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper-linux-x86.zip
      unzip build-wrapper-linux-x86.zip
    displayName: Install buildwrapper
  - bash: |
      autoreconf --install
      ./configure
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all
    displayName: Compile project in build wrapper
  - task: SonarQubeAnalyze@4

- job: BuildLinuxWithSonarCloud
  displayName: Build for Linux With SonarCloud
  dependsOn: []
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    CC: gcc-7
    CXX: g++-7
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'geoffray-adde-sonarsource-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-automake-linux-test'
      cliProjectName: 'geoffray-azure-automake-linux-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      curl 'https://peach.sonarsource.com/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper-linux-x86.zip
      unzip build-wrapper-linux-x86.zip
    displayName: Install buildwrapper
  - bash: |
      autoreconf --install
      ./configure
    workingDirectory: .
    displayName: Prepare build
  - bash: |
      build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all
    displayName: Compile project in build wrapper
  - task: SonarCloudAnalyze@1